[proxmox]
pve01 ansible_host=10.24.44.101
pve02 ansible_host=10.24.44.102
pve03 ansible_host=10.24.44.103

[infra]
monitoring ansible_host=10.24.44.110
ubuntu-git ansible_host=10.24.44.200

[all:vars]
ansible_user=root
