[proxmox]
pve01 ansible_host=10.24.44.101
pve02 ansible_host=10.24.44.102
pve03 ansible_host=10.24.44.103

[infra]
monitoring ansible_host=10.24.44.110
ubuntu-git ansible_host=10.24.44.200

[docker]
vm-dock3 ansible_host=10.24.44.53 ansible_user=ansible vmid=213
vm-dock2 ansible_host=10.24.44.52 ansible_user=ansible vmid=212
vm-dock1 ansible_host=10.24.44.51 ansible_user=ansible vmid=211

[klant_vm_ha]
vm-ha-wp3 ansible_host=10.24.44.123 ansible_user=ansible vmid=123 ssh_user=vm-ha-wp3 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub
vm-ha-wp2 ansible_host=10.24.44.122 ansible_user=ansible vmid=122 ssh_user=vm-ha-wp2 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub
vm-ha-wp1 ansible_host=10.24.44.121 ansible_user=ansible vmid=121 ssh_user=vm-ha-wp1 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub

[klant_lxc]
lxc-wp6 ansible_host=10.24.44.166 ansible_user=ansible ctid=166 ssh_user=lxc-wp6 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub
lxc-wp5 ansible_host=10.24.44.165 ansible_user=ansible ctid=165 ssh_user=lxc-wp5 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub
lxc-wp4 ansible_host=10.24.44.164 ansible_user=ansible ctid=164 ssh_user=lxc-wp4 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub
lxc-wp3 ansible_host=10.24.44.163 ansible_user=ansible ctid=163 ssh_user=lxc-wp3 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub
lxc-wp2 ansible_host=10.24.44.162 ansible_user=ansible ctid=162 ssh_user=lxc-wp2 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub
lxc-wp1 ansible_host=10.24.44.161 ansible_user=ansible ctid=161 ssh_user=lxc-wp1 ssh_key_file=/home/monitoring/.ssh/id_ed25519.pub

[all:vars]
ansible_user=root
