[proxmox]
pve01 ansible_host=10.24.44.101
pve02 ansible_host=10.24.44.102
pve03 ansible_host=10.24.44.103

[infra]
monitoring ansible_host=10.24.44.110
ubuntu-git ansible_host=10.24.44.200

[docker]
vm-ha-dock1 ansible_host=10.24.44.51 ansible_user=ansible vmid=51
vm-ha-dock2 ansible_host=10.24.44.52 ansible_user=ansible vmid=52
vm-ha-dock3 ansible_host=10.24.44.53 ansible_user=ansible vmid=53

[klant_vm_ha]

[klant_lxc]

[all:vars]
ansible_user=root
