---
- name: Basic security for HA VM
  hosts: klant_vm_ha
  become: true

  vars:
    admin_user: ansible
    ssh_public_key: "{{ lookup('file', '/home/monitoring/.ssh/id_ed25519.pub') }}"

  tasks:
    - name: Ensure admin user exists
      ansible.builtin.user:
        name: "{{ admin_user }}"
        groups: sudo
        shell: /bin/bash
        append: true
        create_home: true

    - name: Create .ssh directory
      ansible.builtin.file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: "0700"

    - name: Add SSH key for admin user
      ansible.posix.authorized_key:
        user: "{{ admin_user }}"
        key: "{{ ssh_public_key }}"

    - name: Disable root SSH login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted

      - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Default deny incoming
      ufw:
        direction: incoming
        policy: deny

    - name: Default allow outgoing
      ufw:
        direction: outgoing
        policy: allow

    - name: Allow Zabbix agent
      ufw:
       rule: allow
       port: 10050

    - name: Allow SSH
      ufw:
        rule: allow
        port: 22

    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80

    - name: Allow HTTPS
      ufw:
        rule: allow
        port: 443

    - name: Enable firewall
      ufw:
        state: enabled