---
- import_playbook: provision-vm-docker-cloudinit.yml
- import_playbook: install-zabbix-agent.yml
- import_playbook: install-docker-compose.yml
- import_playbook: docker-swarm.yml
- import_playbook: configure-ha.yml