---
- import_playbook: provision-lxc-wordpress.yml
- import_playbook: install-wordpress.yml
- import_playbook: configure-ha.yml
- import_playbook: install-zabbix-agent.yml
- import_playbook: configure-vm-security.yml
